"""
Django settings for NewsPaper project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8o-%&57^0vks9@-_2urm83&$ru=#n4q3a*(19mtp8-!ctydxke'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost',]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django_filters',
    'django_apscheduler',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

    'author',
    'category',
    'comment',
    'post.apps.PostConfig',
    'sign',
    # 'post_category',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'NewsPaper.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'NewsPaper.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


SITE_ID = 1

STATICFILES_DIRS = [
    BASE_DIR / "static"
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/news'

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION = 'none'


ACCOUNT_FORMS = {'signup': 'sign.forms.BasicSignupForm'}

MAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'mail.gmx.com'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'nbvwzbaotjrclrbea@gmx.com'
EMAIL_HOST_PASSWORD = 'PKXCiWCiW2C3QeJQeiUlRbbj%Joo2C3iUlRbbj'
EMAIL_USE_SSL = True

ADMINS = [
    ('Admin', 'nbvwzbaotjrclrbea@gmx.com'),
]
SERVER_EMAIL = 'nbvwzbaotjrclrbea@gmx.com'
DEFAULT_FROM_EMAIL = 'nbvwzbaotjrclrbea@gmx.com'
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 5
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_EMAIL_VERIFICATION = "optional"
EMAIL_CONFIRMATION_SIGNUP = True

APSCHEDULER_DATETIME_FORMAT = "N j, Y, f:s a"
APSCHEDULER_RUN_NOW_TIMEOUT = 25

BASE_URL = 'http://localhost:8000'
MAX_POST_PER_DAY = 3


CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': os.path.join(BASE_DIR, 'cache_files'),
    }
}

'''LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '{levelname} {message}'
        },
    },

    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },

    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': '/path/to/django/debug.log',
        },
        'console': {
            'level': 'DEBUG',
            #'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
    },

    'loggers': {
        'django': {
            'handlers': ['console'],
            'propagate': True,
        },
        'django.request': {
            'handlers': ['mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        }
    }
}'''

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'formatters': {
        'standart': {
            'style': '{',
            'format': '[{asctime}] [{levelname}]: {message}',
        },
        'standart_with_src': {
            'style': '{',
            'format': '[{asctime}] [{levelname}]: {message} by [{pathname}]',
        },
        'standart_with_stack': {
            'style': '{',
            'format': '[{asctime}] [{levelname}]: {message} by [{pathname}]\nStack:\n{exc_info}',
        },
        'standart_with_module': {
            'style': '{',
            'format': '[{asctime}] [{levelname}] from [{module}]: {message}',
        },
        'standart_full_info': {
            'style': '{',
            'format': '[{asctime}] [{levelname}] by [{pathname}] from [{module}] : {message}\nStack:\n{exc_info}',
        },
        'standart_without_stack': {
            'style': '{',
            'format': '[{asctime}] [{levelname}] by [{pathname}] from [{module}] : {message}',
        },
    },
    
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },

    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'standart',
            'filters': ['require_debug_true'],
        },
        'console_warning': {
            'level': 'WARNING',
            'class': 'logging.StreamHandler',
            'formatter': 'standart_with_src',
            'filters': ['require_debug_true'],
        },
        'console_error': {
            'level': 'ERROR',
            'class': 'logging.StreamHandler',
            'formatter': 'standart_with_stack',
            'filters': ['require_debug_true'],
        },
        'general_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'formatter': 'standart_with_module',
            'filename': 'general.log',
            'filters': ['require_debug_false'],
        },
        'errors_file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'formatter': 'standart_full_info',
            'filename': 'error.log',
        },
        'security_file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'formatter': 'standart_with_module',
            'filename': 'security.log',
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'formatter': 'standart_without_stack',
            'filters': ['require_debug_false'],
        }
    },

    'loggers': {
        'django': {
            'handlers': ['console_warning', 'console_error', 'console', 'general_file'],
            'level': 'DEBUG',
            "propagate": True
        },
        'django.request': {
            'handlers': ['errors_file', 'mail_admins', ],
            'level': 'ERROR',
            "propagate": True
        },
        'django.server': {
            'handlers': ['errors_file', 'mail_admins',],
            'level': 'ERROR',
            "propagate": True
        },
        'django.template': {
            'handlers': ['errors_file',],
            'level': 'ERROR',
            "propagate": True
        },
        'django.db_backends': {
            'handlers': ['errors_file',],
            'level': 'ERROR',
            "propagate": True
        },
        'django.security': {
            'handlers': ['security_file',],
            'level': 'DEBUG',
            "propagate": True
        },
    }
}
